spring.application.name=VoiceToDoListWithAi
spring.datasource.url=jdbc:mysql://localhost:3306/voiceDB?createTableIfNotExist=true
spring.datasource.username=root
spring.datasource.password=dewancollege@123
#Default password is also root
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=se.hasanjafar@gmail.com
spring.mail.password=sknsunvpuxsapvoo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SSL Configuration
javax.net.ssl.trustStore=${java.home}/lib/security/cacerts
javax.net.ssl.trustStorePassword=changeit
javax.net.ssl.keyStore=${java.home}/lib/security/cacerts
javax.net.ssl.keyStorePassword=changeit